<script setup lang="ts">
import { ref } from 'vue';
import { useDeck, stageLabel } from '../../shared/useDeck';
import SessionTerminal from './SessionTerminal.vue';
import ModalDialog from '../../shared/ModalDialog.vue';
defineEmits<{ launch: [] }>();
const deck = useDeck(); const { state, activeSession, busy } = deck;
const renameOpen = ref(false); const newName = ref(''); const resumeOpen = ref(false); const allowUnverified = ref(false);
async function resume() { await deck.perform('Resuming original CLI history', async () => { await deck.call('resume_session', { id: activeSession.value?.id, allowUnverified: allowUnverified.value }); resumeOpen.value = false; }); }
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">LOCAL CODING SESSIONS</div><h1>{{ activeSession?.name ?? 'Pick up where you left off.' }}</h1><p>{{ activeSession?.projectPath ?? 'Each terminal stays bound to the deployment it started with.' }}</p></div><button class="button primary" @click="$emit('launch')">+ New session</button></div>
  <div v-if="!activeSession" class="empty-card"><div class="empty-symbol">⌘</div><h2>{{ state?.sessions.length ? 'Choose a session in the sidebar.' : 'A terminal, already connected.' }}</h2><p>Once your endpoint is enabled, open Codex or Claude Code with its own provider configuration and local history.</p><button class="button ghost" @click="$emit('launch')">Open a coding session</button></div>
  <section v-else class="terminal-panel"><header class="terminal-toolbar"><div class="terminal-label"><span :class="['dot', activeSession.status]" /><strong>{{ activeSession.cli === 'codex' ? 'Codex' : 'Claude Code' }}</strong><span>{{ activeSession.model }}</span><span class="tag">{{ stageLabel(activeSession.status) }}</span></div><div class="button-row"><button class="text-button" @click="newName = activeSession.name; renameOpen = true">Rename</button><button v-if="activeSession.status !== 'ended'" class="button ghost compact" :disabled="!!busy" @click="deck.perform('Interrupting CLI', () => deck.call('terminal_input', { id: activeSession?.id, data: '\u0003' }))">Interrupt</button><button v-if="activeSession.status !== 'ended'" class="button ghost compact" :disabled="!!busy" @click="deck.perform('Closing local session', () => deck.call('close_session', { id: activeSession?.id }))">Close session</button><button v-else class="button ghost compact" :disabled="!!busy" @click="resumeOpen = true">Open resume history</button></div></header><div class="terminal-binding">Deployment {{ activeSession.deploymentId }} · {{ activeSession.unverifiedCombination ? 'Candidate test — unverified compatibility' : 'Validated combination' }}</div><SessionTerminal :key="activeSession.id" :session-id="activeSession.id" /><footer class="terminal-footer">Closing this session leaves its Pod running unless you enabled idle cleanup. CLI approval prompts remain active.</footer></section>
  <ModalDialog v-if="renameOpen" title="Rename session" :busy="!!busy" @close="renameOpen = false"><form @submit.prevent="deck.perform('Renaming session', async () => { await deck.call('rename_session', { id: activeSession?.id, name: newName }); renameOpen = false; })"><label>Name<input v-model="newName" maxlength="80" required /></label><footer class="dialog-actions"><button class="button primary" :disabled="!!busy">Save name</button></footer></form></ModalDialog>
  <ModalDialog v-if="resumeOpen" title="Resume the original conversation" :busy="!!busy" @close="resumeOpen = false"><p class="dialog-copy">Resume keeps the original model and deployment. The original Pod must still be ready. If it was terminated, open a new session after provisioning and enabling a new Pod.</p><label class="checkbox"><input v-model="allowUnverified" type="checkbox" /><span>Allow resuming this candidate test without complete compatibility evidence.</span></label><footer class="dialog-actions"><button class="button ghost" @click="resumeOpen = false">Cancel</button><button class="button primary" :disabled="!!busy" @click="resume">Resume history</button></footer></ModalDialog>
</template>
