<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useDeck, elapsed, money, stageLabel } from '../../shared/useDeck';
import type { Hardware } from '../../shared/contracts';
import ModalDialog from '../../shared/ModalDialog.vue';
import ModelDetails from '../models/ModelDetails.vue';
import ModelHardwareSuggestion from '../models/ModelHardwareSuggestion.vue';
defineEmits<{ launch: [] }>();
const deck = useDeck();
const { state, snapshot, profile, selectedProfileId, hardware, activeDeployment: deployment, busy, error, connected, clock } = deck;
const selectedImported = computed(() => state.value?.importedModels.find(model => model.id === profile.value?.model.id));
const gpu = ref(''); const dataCenter = ref(''); const volume = ref('');
const provisionConfirm = ref(false); const finishConfirm = ref(false); const absenceConfirm = ref(false); const typedName = ref('');
watch(profile, p => { gpu.value = p?.model.gpuTypes[0] ?? ''; dataCenter.value = ''; volume.value = ''; }, { immediate: true });
watch(dataCenter, () => { volume.value = ''; });
const locations = computed(() => hardware.value?.dataCenters.filter(dc => dc.gpuAvailability.some(g => g.gpuTypeId === gpu.value && ['high', 'medium', 'low'].includes(g.stockStatus?.toLowerCase() ?? ''))) ?? []);
const volumes = computed(() => hardware.value?.networkVolumes.filter(v => v.dataCenterId === dataCenter.value) ?? []);
const rate = computed(() => (hardware.value?.gpus.find(g => g.id === gpu.value)?.securePrice ?? 0) * (profile.value?.model.gpuCount ?? 1));
const cost = computed(() => deployment.value ? (clock.value - deployment.value.createdAt) / 3600 * deployment.value.hourlyUsd : 0);
const activeSessions = computed(() => state.value?.sessions.filter(s => s.deploymentId === deployment.value?.id && s.status !== 'ended') ?? []);
const stageNumber = computed(() => deployment.value?.stage === 'ready' ? 2 : deployment.value ? 1 : 0);
async function refreshHardware() { await deck.perform('Checking current GPU availability', async () => { hardware.value = await deck.call<Hardware>('hardware'); }); }
async function provision() {
  const id = await deck.perform('Provisioning Runpod', () => deck.call<string>('provision', { request: { profileId: selectedProfileId.value, gpuType: gpu.value, dataCenterId: dataCenter.value, networkVolumeId: volume.value || null, acknowledgePaidCreation: true } }));
  if (id) provisionConfirm.value = false;
}
async function finish() {
  await deck.perform('Finishing deployment', () => deck.call('finish', { id: deployment.value?.id }));
  if (!error.value) finishConfirm.value = false;
}
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">TEMPORARY COMPUTE · LOCAL CODE</div><h1>Your model. Your workspace.</h1><p>Bring up a GPU, enable its endpoint, and open your coding CLI.</p></div><span class="pill"><span :class="['dot', deployment ? 'loading' : '']" />{{ deployment ? stageLabel(deployment.stage) : 'No active Pod' }}</span></div>
  <div class="workflow"><div :class="{ current: stageNumber === 0, done: stageNumber > 0 }"><span>01</span><strong>Provision Runpod</strong><small>Choose model and compute</small></div><b>→</b><div :class="{ current: stageNumber === 1, done: connected }"><span>02</span><strong>Enable endpoint</strong><small>Select routing when ready</small></div><b>→</b><div :class="{ current: connected }"><span>03</span><strong>Open your CLI</strong><small>Code in your local project</small></div></div>
  <div class="stats-grid"><div class="stat-card"><span>GPU rate</span><strong>{{ deployment ? money(deployment.hourlyUsd) : '—' }}<small>/ hour</small></strong><p>Limit {{ money(state?.settings.policy.maxHourlyUsd ?? snapshot?.hourlyCeilingUsd ?? 0) }}/h</p></div><div class="stat-card"><span>Elapsed runtime</span><strong class="time-value">{{ deployment ? elapsed(clock - deployment.createdAt) : 'Not running' }}</strong><p>Includes startup and idle time</p></div><div class="stat-card"><span>Estimated GPU cost</span><strong>{{ money(cost) }}</strong><p>Estimate, not an invoice or exact cap</p></div><div class="stat-card"><span>Local sessions</span><strong>{{ activeSessions.length }}<small>/ {{ deployment?.profile.model.maxSessions ?? '—' }}</small></strong><p>Configured capacity</p></div></div>
  <section v-if="!deployment" class="panel provision-panel">
    <div class="panel-heading"><div><h2>Prepare your deployment</h2><p>A provisioned GPU starts billing before you enable it.</p></div><span class="tag">SECURE CLOUD</span></div>
    <div class="form-grid">
      <label>Model profile<select v-model="selectedProfileId"><option v-for="p in snapshot?.catalog" :key="p.model.id" :value="p.model.id">{{ p.model.displayName }} · candidate</option></select></label>
      <label>GPU configuration<select v-model="gpu"><option v-for="g in profile?.model.gpuTypes" :key="g" :value="g">{{ profile?.model.gpuCount }} × {{ g }}</option></select></label>
      <label>Location<select v-model="dataCenter"><option value="">{{ hardware ? 'Choose available location' : 'Check availability first' }}</option><option v-for="dc in locations" :key="dc.id" :value="dc.id">{{ dc.location }} · {{ dc.id }}</option></select></label>
      <label>Model storage<select v-model="volume"><option value="">Fully temporary · download each run</option><option v-for="v in volumes" :key="v.id" :value="v.id" :disabled="v.size < (profile?.model.minCacheGb ?? 0)">Retain {{ v.name }} · {{ v.size }} GB{{ v.size < (profile?.model.minCacheGb ?? 0) ? ' · too small' : '' }}</option></select></label>
    </div>
    <div v-if="selectedImported" class="model-overview selected-model-details section-gap"><ModelDetails :metadata="selectedImported.metadata" /><ModelHardwareSuggestion :model="selectedImported" /></div>
    <p v-if="profile" class="small muted">Model cache requirement: {{ profile.model.minCacheGb }} GB, including working space. Available space is also checked inside the Pod before downloading.</p>
    <div class="storage-note"><span>↳</span>{{ volume ? 'This network volume survives Pod termination and continues to incur storage charges. Storage costs are separate from the GPU estimate.' : 'Pod-local model files are removed on termination. Your local project and CLI history stay on this Mac.' }}</div>
    <div v-if="!state?.settings.policy.paidProvisioningEnabled" class="notice">Paid provisioning is disabled for this build’s initial setup. When you are ready to test, set your total budget and lifetime in <button class="inline-button" @click="deck.view.value = 'setup'">Setup</button>.</div>
    <footer class="panel-footer"><div><strong>{{ rate ? `${money(rate)}/hour` : 'Check availability for current pricing' }}</strong><small>{{ state?.settings.policy.maxLifetimeMinutes ? `Maximum lifetime: ${state.settings.policy.maxLifetimeMinutes} minutes` : 'Maximum lifetime has not been set' }}</small></div><div class="button-row"><button class="button ghost" :disabled="!!busy || !snapshot?.runpodKeyConfigured" @click="refreshHardware">Check availability</button><button class="button primary" :disabled="!!busy || !state?.settings.policy.paidProvisioningEnabled || !profile || !dataCenter || !rate || rate > state.settings.policy.maxHourlyUsd" @click="provisionConfirm = true">Provision Runpod →</button></div></footer>
  </section>
  <section v-else class="panel">
    <div class="panel-heading"><div><div class="eyebrow">CURRENT DEPLOYMENT</div><h2>{{ deployment.profile.model.displayName }}</h2><p>{{ deployment.gpuCount }} × {{ deployment.gpuType }} · {{ deployment.dataCenterId }}</p></div><span :class="['tag', deployment.stage === 'ready' ? 'green' : 'amber']">{{ stageLabel(deployment.stage) }}</span></div>
    <div class="deployment-status"><span :class="['dot', deployment.stage]" /><div><strong>{{ deployment.message }}</strong><p v-if="deployment.cleanupDueAt">Last session ended. Auto-termination in {{ elapsed(deployment.cleanupDueAt - clock) }}. Opening a session cancels this countdown.</p><p>Local lifetime countdown: {{ elapsed(deployment.deadlineAt - clock) }} · {{ activeSessions.length }} affected sessions</p></div></div>
    <div v-if="deployment.failureReason" class="notice warning">{{ deployment.failureReason }} <a @click="deck.openExternal" :href="`https://huggingface.co/${deployment.profile.model.repository}`" target="_blank" rel="noreferrer">Model page ↗</a></div>
    <div class="binding"><span>{{ state?.enabledDeploymentId === deployment.id ? 'SELECTED FOR NEW SESSIONS' : 'NOT ENABLED' }}</span><strong>{{ state?.enabledDeploymentId === deployment.id && !connected ? 'Selection needs revalidation' : deployment.profile.model.servedModel }}</strong><small>Existing sessions retain their original deployment.</small></div>
    <div class="button-row wrap"><button class="button ghost" :disabled="!!busy" @click="deck.perform('Reconciling with Runpod', () => deck.call('reconcile'))">Reconcile</button><button class="button primary" :disabled="!!busy || deployment.stage !== 'ready'" @click="deck.perform('Verifying and enabling endpoint', () => deck.call('enable', { id: deployment?.id }))">{{ state?.enabledDeploymentId === deployment.id ? 'Revalidate endpoint' : 'Enable endpoint' }}</button><button class="button ghost" :disabled="!connected || !!busy" @click="$emit('launch')">Open CLI</button><button class="button danger push-right" :disabled="!!busy" @click="finishConfirm = true">Finish deployment</button></div>
    <details class="advanced"><summary>Deployment details and recovery</summary><dl><dt>Pod name</dt><dd>{{ deployment.podName }}</dd><dt>Pod identities</dt><dd>{{ deployment.podIds.join(', ') || 'Create response not confirmed' }}</dd><dt>Storage</dt><dd>{{ deployment.networkVolumeId ? `Retained volume ${deployment.networkVolumeId}; ongoing storage charges separate` : 'Ephemeral' }}</dd><dt>Profile version</dt><dd>{{ deployment.profile.model.version }} · {{ deployment.profile.fingerprint }}</dd></dl><a @click="deck.openExternal" href="https://console.runpod.io/pods" target="_blank" rel="noreferrer">Open Runpod console ↗</a><button v-if="!deployment.podIds.length" class="text-button" :disabled="!!busy" @click="absenceConfirm = true">Resolve an absent creation</button></details>
  </section>
  <div class="bottom-grid"><div class="callout"><span class="callout-icon">⌘</span><div><h3>Your normal subscriptions stay separate.</h3><p>App sessions use their own CLI state and explicit endpoint credentials. Your normal terminal sessions keep their existing configuration.</p></div></div><div class="callout"><span class="callout-icon amber-text">◷</span><div><h3>Keep an eye on running compute.</h3><p>The local timer cannot protect you while the app is closed or offline. Confirm Pod deletion in Runpod when you finish.</p></div></div></div>
  <section v-if="state?.deployments.some(d => d.stage === 'terminated')" class="history"><h3>Recent deployments</h3><div v-for="past in state.deployments.filter(d => d.stage === 'terminated').slice().reverse()" :key="past.id" class="history-row"><strong>{{ past.profile.model.displayName }}</strong><span :title="past.failureReason ?? past.message">{{ past.failureReason ? 'Startup failed · cleanup confirmed' : new Date(past.createdAt * 1000).toLocaleString() }}</span><span>{{ money(((past.terminatedAt ?? clock) - past.createdAt) / 3600 * past.hourlyUsd) }} estimated</span><span class="tag">TERMINATED</span></div></section>
  <ModalDialog v-if="provisionConfirm" title="Provision paid GPU compute?" :busy="!!busy" @close="provisionConfirm = false"><p class="dialog-copy">{{ profile?.model.displayName }} · {{ gpu }} · {{ dataCenter }}. Current estimate {{ money(rate) }}/hour. This candidate has not passed a live coding test.</p><div class="notice warning">The provider’s final rate is checked after creation. If it exceeds your limit, the app requests cleanup; brief charges can still occur. The local timer is not an offline spending cap.</div><p class="small muted">Total experiment budget: {{ money(state?.settings.policy.totalBudgetUsd ?? 0) }} · maximum lifetime: {{ state?.settings.policy.maxLifetimeMinutes }} minutes. Retained storage, if selected, is billed separately.</p><footer class="dialog-actions"><button class="button ghost" :disabled="!!busy" @click="provisionConfirm = false">Cancel</button><button class="button primary" :disabled="!!busy" @click="provision">Create paid Pod</button></footer></ModalDialog>
  <ModalDialog v-if="finishConfirm" title="Finish this deployment?" :busy="!!busy" @close="finishConfirm = false"><p class="dialog-copy">This interrupts {{ activeSessions.length }} local session(s) and terminates their shared Pod. Local project files, CLI histories, and retained network volumes are preserved.</p><ul class="affected-sessions"><li v-for="session in activeSessions" :key="session.id">{{ session.name }} · {{ session.cli }}</li></ul><footer class="dialog-actions"><button class="button ghost" :disabled="!!busy" @click="finishConfirm = false">Cancel</button><button class="button danger" :disabled="!!busy" @click="finish">Interrupt sessions and terminate</button></footer></ModalDialog>
  <ModalDialog v-if="absenceConfirm" title="Resolve an unconfirmed creation" :busy="!!busy" @close="absenceConfirm = false"><p class="dialog-copy">Check the Runpod console for the exact Pod name below. Wait at least two minutes after creation. The app will check the provider list again before clearing this record.</p><p class="code-value">{{ deployment?.podName }}</p><label>Type the Pod name to confirm it is absent<input v-model="typedName" autocomplete="off" /></label><footer class="dialog-actions"><button class="button ghost" @click="absenceConfirm = false">Cancel</button><button class="button primary" :disabled="!!busy || typedName !== deployment?.podName" @click="deck.perform('Confirming absence', async () => { await deck.call('confirm_absent_creation', { id: deployment?.id, typedName }); absenceConfirm = false; })">Verify absence</button></footer></ModalDialog>
</template>
